services:
  db:
    image: postgres:16
    container_name: sklad_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sklad
      POSTGRES_PASSWORD: skladpass
      POSTGRES_DB: sklad
    ports:
      - "5432:5432"
    volumes:
      - sklad_pgdata:/var/lib/postgresql/data

  converter:
    image: linuxserver/libreoffice:latest
    container_name: sklad_converter
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - ./tmp-convert:/work

volumes:
  sklad_pgdata: